# Spring boot application
spring:
  application:
    name: dubbo-provider-demo

server:
  port: 8081
  # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service

dubbo:
  scan:
    base-packages: com.tuling.provider.service
  application:
    name: ${spring.application.name}
  ## Dubbo Registry
  registry:
    address: zookeeper://127.0.0.1:2181
  ## Dubbo Protocols
  protocols:
    p1:
      id: dubbo1
      name: dubbo
      port: 20881
      host: 0.0.0.0
    p2:
      id: rest
      name: rest
      port: 8083
      host: 0.0.0.0



